import { model, setModelTiers } from './shared/models'
import type { LanePlanDigest, LaneOutcome, SetupResult, LaneResult, MergeResult, DocsResult, TddActArgs, RepoConfig } from './shared/types'
import { buildWaves, packWaves, parseAgentJson, resolveLanePlanPath, epicSlug } from './shared/utils'
import { laneStateReadScript } from './shared/prompts'
import { batchCommandPrompt, setBatchCacheKey, setBatchRoot, parseBatchResult, stepStdout, describeFailure, type BatchResult } from './shared/batch'
import { actStartSteps, lanePlanDigestFromSteps, digestSpecHash, cleanupSteps } from './shared/lane-steps'
import { runBatch } from './shared/agents'
import { DEFAULT_CONFIG, skillPath } from './shared/models'
import { configReadSteps, configFromSteps } from './shared/config-steps'
import { stageOpts, bootstrapOpts, configureAgentTypes, readAgentTypeConfig, agentTypeArgs } from './shared/agent-types'

export const meta = {
  name: 'datum-tdd-act',
  description: 'Deterministic TDD Act: RED->GREEN->REFACTOR per lane with gate enforcement',
  phases: [],
}

// ── Parse args ──
// "yolo" mode: auto-detect epicBranch from current git branch, generate runId from timestamp

const rawArgs: string = typeof args === 'string' ? args.trim().replace(/^"|"$/g, '').trim() : ''
const a = ((typeof args === 'string')
  ? (rawArgs.toLowerCase() === 'yolo' ? { yolo: true } : JSON.parse(args))
  : (args || {})) as TddActArgs

// Resume cache key (#354): stamped into every batch prompt of this run.
setBatchCacheKey(a.configFingerprint || '')
setBatchRoot(typeof a.repoRoot === 'string' ? a.repoRoot : '')

// Read config from .datum/config.json if not passed as args
let repoCfg: RepoConfig = {} as RepoConfig
if (!a.testCommand || !a.language) {
  const configReadStepList = configReadSteps()
  const configBatch = await runBatch(configReadStepList, bootstrapOpts('cli', { label: 'read-config', model: model('fast') }))
  repoCfg = { ...DEFAULT_CONFIG, ...configFromSteps(configBatch) } as RepoConfig
}
if (repoCfg.models && typeof repoCfg.models === 'object') setModelTiers(repoCfg.models)
// #368: agent_types / hooks_installed switches for this and every child workflow.
configureAgentTypes(readAgentTypeConfig(repoCfg))
const sk = (name: string) => skillPath(repoCfg.skills_dir || '', name)
const testCommand: string = a.testCommand || repoCfg.test_command || DEFAULT_CONFIG.test_command
const language: string = a.language || repoCfg.language || DEFAULT_CONFIG.language
const test_framework: string | undefined = a.test_framework || repoCfg.test_framework

let epicBranch: string = a.epicBranch || ''
let runId: string = a.runId || ''

// yolo mode: auto-detect branch and generate runId; then resolve + read the
// lane plan (lane-plan-final.json first, #232/#237) and the epic-scoped
// completion markers — ONE datum-cli call (#368) where there were four.
const actStart = actStartSteps({
  branch: epicBranch ? epicBranch : (a.yolo ? 'detect' : ''),
  lanePlanPath: a.lanePlanPath || null,
  laneStateReadScript: laneStateReadScript({
    epicBranch: '$__eb', epicSlug: '', taskIdsSpace: `$(jq -r '.topological_order[]' "$__plan")`,
  }),
})
if (!epicBranch && !a.yolo) throw new Error('args.epicBranch is required. Pass {epicBranch, runId} or "yolo" to auto-detect.')
const actStartRaw = await agent(
  batchCommandPrompt(actStart),
  stageOpts('cli', { label: 'act-start', phase: 'Topology', model: model('fast') }),
)
const actStartResult = parseBatchResult(actStartRaw, actStart)
epicBranch = epicBranch || (stepStdout(actStartResult, 'branch') || '').trim()
runId = runId || (stepStdout(actStartResult, 'timestamp') || '').trim()

if (!epicBranch) throw new Error(`args.epicBranch is required and auto-detect failed (${describeFailure(actStartResult, 'act-start')}). Pass {epicBranch, runId} or "yolo" to auto-detect.`)
if (!runId) throw new Error(`args.runId is required and auto-detect failed (${describeFailure(actStartResult, 'act-start')}). Pass {epicBranch, runId} or "yolo" to auto-detect.`)

const epicDir: string = `docs/epics/${epicBranch}`
const lanePlanPath: string = a.lanePlanPath || resolveLanePlanPath(epicDir, stepStdout(actStartResult, 'resolve') || '')
// Pre-generated RED skeletons from the Plan phase (datum-go passes the same).
const skeletonDir = `docs/epics/${epicBranch}/skeletons`

// ── Topology ──

phase('Topology')

// The plan never travels through an LLM turn. A reader echo normalised
// "§4" → "§ 4" inside acceptance criteria (wf_6bfbd9f2-510: spec hashes
// changed, completed lanes re-ran); the base64 chunk relay that replaced it
// was GENERATED by the runner past ~2.7 KB rather than copied
// (wf_5791e11f-693). The scheduler runs on the compact digest
// `datum lane-plan-digest` wrote in the act-start batch, byte-verified
// (wc -c + git hash-object); each lane fetches its own full spec at intake.
const digestResult = lanePlanDigestFromSteps(actStartResult, lanePlanPath)
if (!digestResult.ok || !digestResult.digest) throw new Error(digestResult.error)
const lanePlan: LanePlanDigest = digestResult.digest

const waves = buildWaves(lanePlan)
if (waves.length === 0 || Object.keys(lanePlan.lanes || {}).length === 0) {
  throw new Error('Lane plan has 0 tasks — nothing to execute')
}
log(`Topology: ${lanePlan.total_lanes} lanes in ${waves.length} waves`)
for (let i = 0; i < waves.length; i++) {
  log(`  Wave ${i}: [${waves[i].join(', ')}]`)
}

// ── Epic-scoped completion markers ──
// Lanes merged in prior runs/sessions skip entirely. A marker counts only if
// status=completed, spec_hash matches the current plan entry, and merge_commit
// is an ancestor of the epic branch tip.

const slug = epicSlug(epicBranch)
// Safe: an unparseable result yields {} — no lane matches any prior marker,
// so every lane is treated as NOT already merged. That's the conservative
// direction (a lane redundantly re-runs instead of a real completed lane
// being wrongly skipped), never the direction that would silently let a
// phase "pass" on missing evidence.
const priorMarkers = parseAgentJson(stepStdout(actStartResult, 'lane-state-read') || '', {}) as Record<string, { status: string; spec_hash: string; ancestor: boolean }>
const alreadyMerged = lanePlan.topological_order.filter((id: string) => {
  const m = priorMarkers[id]
  return !!m && m.status === 'completed' && m.ancestor === true && m.spec_hash === digestSpecHash(lanePlan, id)
})

const results: Record<string, LaneOutcome> = {}
const failures: string[] = []
const completedLanes: string[] = []
for (const id of alreadyMerged) {
  results[id] = { task_id: id, status: 'completed' }
  completedLanes.push(id)
}
if (alreadyMerged.length > 0) {
  log(`Epic-scoped state: ${alreadyMerged.length} lane(s) already merged, skipping: [${alreadyMerged.join(', ')}]`)
}

// ── Batch partitioning ──

const MAX_BATCH = 5
const allLaneIds = lanePlan.topological_order.filter((id: string) => !alreadyMerged.includes(id))
const remainingWaves = waves
  .map((wave) => wave.filter((id) => allLaneIds.includes(id)))
  .filter((wave) => wave.length > 0)
const batches: string[][] = packWaves(remainingWaves, MAX_BATCH, lanePlan)
log(`Wave-packed ${allLaneIds.length} tasks into ${batches.length} batches`)

if (batches.length > 1) {
  log(`Auto-partitioned ${allLaneIds.length} tasks into ${batches.length} batches (max ${MAX_BATCH}/batch)`)
  for (let b = 0; b < batches.length; b++) {
    log(`  Batch ${b}: [${batches[b].join(', ')}]`)
  }
}

// ── Batch loop ──

for (let bi = 0; bi < batches.length; bi++) {
  const batchLaneIds = batches[bi]
  const batchTag = batches.length > 1 ? ` [batch ${bi + 1}/${batches.length}]` : ''
  const batchRunId = batches.length > 1 ? `${runId}-b${bi}` : runId

  if (batches.length > 1) log(`\n${'='.repeat(60)}\n=== Batch ${bi + 1}/${batches.length}: [${batchLaneIds.join(', ')}] ===\n${'='.repeat(60)}`)

  // Cross-batch dependency check: block lanes whose deps failed/were blocked,
  // skip lanes whose deps never ran. Failed deps are NOT satisfied deps.
  for (const lid of batchLaneIds) {
    const deps: string[] = lanePlan.lanes[lid]?.depends_on || []
    const unmet = deps.filter((d: string) => !batchLaneIds.includes(d) && !completedLanes.includes(d))
    if (unmet.length === 0) continue
    const failedDeps = unmet.filter((d: string) => failures.includes(d) || results[d]?.status === 'blocked')
    const neverRan = unmet.filter((d: string) => !failedDeps.includes(d))
    const rootCauses = failedDeps.map((d: string) => `${d}@${results[d]?.stage || '?'}`)
    const detail = [
      rootCauses.length > 0 ? `dep(s) failed/blocked: [${rootCauses.join(', ')}]` : '',
      neverRan.length > 0 ? `dep(s) never ran: [${neverRan.join(', ')}]` : '',
    ].filter(Boolean).join('; ')
    results[lid] = { task_id: lid, status: 'blocked', stage: 'SKIPPED', error: `blocked — ${detail}` }
    log(`  BLOCKED ${lid}: ${detail}`)
  }
  const runnableBatchIds = batchLaneIds.filter((id: string) => !results[id])
  if (runnableBatchIds.length === 0) {
    log(`Batch ${bi} fully skipped — all lanes have unmet deps`)
    continue
  }

  try {
    // Setup
    log('── Setup ──')
    const setup = await workflow(
      { scriptPath: sk('datum-tdd-act-setup') },
      { batchRunId, epicBranch, batchLaneIds: runnableBatchIds, lanePlan, lanePlanPath, batchTag, agentTypes: agentTypeArgs(), configFingerprint: a.configFingerprint || '', repoRoot: a.repoRoot || '' }
    ) as SetupResult

    // Act
    log('── Act ──')
    const act = await workflow(
      { scriptPath: sk('datum-tdd-act-lane') },
      {
        batchLaneIds: runnableBatchIds, lanePlan, worktreePaths: setup.worktreePaths, batchTag,
        cfg: { lanePlanPath, epicBranch, runId: batchRunId, testCommand, language, test_framework, skeletonDir, yolo: !!a.yolo, agentTypes: agentTypeArgs(), configFingerprint: a.configFingerprint || '', repoRoot: a.repoRoot || '' },
        priorFailures: failures,
        priorCompleted: completedLanes,
      }
    ) as LaneResult

    // Collect results
    for (const [id, r] of Object.entries(act.results || {})) {
      results[id] = r
      if (!r || r.status === 'failed') {
        failures.push(id)
        log(`  FAILED ${id}: ${r ? `${r.stage} — ${r.error}` : 'null result'}`)
      } else if (r.status === 'skipped' || r.status === 'blocked') {
        log(`  ${r.status.toUpperCase()} ${id}: ${r.error || 'dependency failed'}`)
      } else {
        completedLanes.push(id)
      }
    }
    log(`Act${batchTag} done: ${batchLaneIds.filter(id => completedLanes.includes(id)).length}/${batchLaneIds.length} succeeded`)

    // #356: a GREEN that is blocked on write access outside allowed_write_files
    // is surfaced ONCE, as a single lead-approval question — not retried blind.
    const approvals = Object.values(act.results || {}).filter(
      (r): r is LaneOutcome => !!r && r.status === 'blocked' && r.stage === 'GREEN' && Array.isArray(r.needs_write),
    )
    if (approvals.length > 0) {
      log(`\nLEAD APPROVAL NEEDED${batchTag} — GREEN is blocked on files outside allowed_write_files:`)
      for (const r of approvals) {
        log(`  ${r.task_id}: needs_write=[${(r.needs_write || []).join(', ')}]`)
        log(`    ${r.error}`)
      }
      log('  To approve: add the listed paths to that lane\'s `files` in lane-plan.json, then re-run act (datum go --start-from act). In yolo mode, paths inside src/ are widened automatically and GREEN re-runs once.')
    }

    // Merge + Cleanup. The epic-scoped completion markers (so future runs/
    // sessions skip these lanes) are written by the merge workflow in the same
    // datum-cli call as the squash merge (#368).
    log('── Merge ──')
    const mergedIds = batchLaneIds.filter(id => completedLanes.includes(id))
    const mergeResult = await workflow(
      { scriptPath: sk('datum-tdd-act-merge') },
      {
        epicBranch,
        completedIds: mergedIds,
        results,
        batchRunId,
        topoOrder: lanePlan.topological_order,
        batchTag,
        agentTypes: agentTypeArgs(),
        configFingerprint: a.configFingerprint || '',
        repoRoot: a.repoRoot || '',
        laneState: mergedIds.length > 0
          ? { epicSlug: slug, entries: mergedIds.map(id => ({ task_id: id, spec_hash: digestSpecHash(lanePlan, id) })) }
          : null,
      }
    ) as MergeResult | null

    // Same rule as datum-go: a completed lane whose squash-merge did not land
    // shipped nothing — demote it so the summary and triage tell the truth.
    // Only the lanes the merge did not land are demoted: on a partial merge
    // the earlier lanes are committed and kept (LaneMergeError).
    if (mergedIds.length > 0 && (!mergeResult || mergeResult.failed || !mergeResult.merged)) {
      const failedLane = mergeResult && typeof mergeResult.failedLane === 'string' ? mergeResult.failedLane : ''
      const why = mergeResult
        ? (failedLane ? `squash-merge of ${failedLane} did not land` : 'squash-merge step exited non-zero')
        : 'merge workflow returned null'
      const landed = new Set(mergeResult && Array.isArray(mergeResult.mergedIds) ? mergeResult.mergedIds : [])
      const unmerged = mergedIds.filter((id) => !landed.has(id))
      // The git-level reason travels with the demotion (elonchesd task-015).
      const conflictFiles = mergeResult && Array.isArray(mergeResult.conflictFiles) ? mergeResult.conflictFiles : []
      const reason = mergeResult && typeof mergeResult.error === 'string' ? mergeResult.error.slice(0, 300) : ''
      const detail = `${conflictFiles.length > 0 ? ` — conflicted files: [${conflictFiles.join(', ')}]` : ''}${reason ? ` — ${reason}` : ''}${mergeResult && mergeResult.report ? ` (report: ${mergeResult.report})` : ''}`
      for (const id of unmerged) {
        const i = completedLanes.indexOf(id)
        if (i >= 0) completedLanes.splice(i, 1)
        failures.push(id)
        results[id] = { task_id: id, status: 'failed', stage: 'MERGE', error: `merge_failed: ${why}${detail}${batchTag}` }
      }
      log(`Merge${batchTag} FAILED — demoted [${unmerged.join(', ')}] from completed to failed (${why})${landed.size > 0 ? `; landed: [${[...landed].join(', ')}]` : ''}`)
    }
  } catch (exc) {
    // A throw in setup/lanes/merge must not abort the script with no
    // summary and no triage after earlier batches merged (phase review
    // wf_9a69f891-462): fail this batch's runnable lanes by name and go on —
    // later batches that depend on them are blocked by the dep check.
    const message = (exc as Error).message
    log(`act_batch_failed: batch ${bi + 1}/${batches.length} — ${message}`)
    for (const id of runnableBatchIds) {
      if (results[id] && results[id].status === 'completed') continue
      results[id] = { task_id: id, status: 'failed', stage: 'CRASH', error: `act_batch_failed: ${message}` }
      if (!failures.includes(id)) failures.push(id)
    }
    // The merge child (where cleanup lives) never ran: deregister this
    // batch's root and lane worktrees so the next run's setup does not die
    // on "already used by worktree" (caliper BUG O). Lane branches with
    // commits are preserved by the CLI. Fail-soft: a cleanup failure is
    // logged, never a second crash.
    try {
      const cleanup = await runBatch(cleanupSteps(batchRunId, epicBranch), stageOpts('cli', { label: `cleanup-after-crash${batchTag}`, phase: 'Act', model: model('fast') }))
      log(`  cleanup${batchTag}: ${stepStdout(cleanup, 'cleanup') || describeFailure(cleanup, 'cleanup')}`)
    } catch (cleanupExc) {
      log(`[warn] cleanup_after_crash_failed${batchTag}: ${(cleanupExc as Error).message}`)
    }
  }
}

// ── Docs ──

log('── Docs ──')
// Fails soft: a docs failure lands in the summary, never aborts the run.
let docsResult: DocsResult | null = null
try {
  docsResult = await workflow(
    { scriptPath: sk('datum-tdd-act-docs') },
    { completedLanes, lanePlan, runId, agentTypes: agentTypeArgs(), configFingerprint: a.configFingerprint || '', repoRoot: a.repoRoot || '' }
  ) as DocsResult | null
} catch (exc) {
  log(`[warn] docs_workflow_failed: ${(exc as Error).message} — continuing; docs may be stale or left uncommitted`)
  docsResult = { synced: false, committed: false, failure_reason: `docs_workflow_failed: ${(exc as Error).message}` } as DocsResult
}
if (docsResult && docsResult.committed === false) {
  log(`[warn] Docs sync wrote [${(docsResult.files || []).join(', ')}] but the commit was refused: ${docsResult.failure_reason || 'unknown'} — the files are left modified in the checkout`)
} else if (docsResult && docsResult.failure_reason) {
  // Nothing was written, but the phase did not do its job: say so by name
  // (docs_check_no_result, "wrote no files", ...) instead of reading as synced.
  log(`[warn] Docs sync did not complete: ${docsResult.failure_reason}`)
}

// ── Summary ──

const skippedLanes = Object.keys(results).filter(id => results[id]?.status === 'skipped')
const blockedLanes = Object.keys(results).filter(id => results[id]?.status === 'blocked')

log(`\n${'═'.repeat(60)}`)
log(`ACT COMPLETE: ${completedLanes.length}/${lanePlan.total_lanes} succeeded, ${failures.length} failed, ${skippedLanes.length} skipped, ${blockedLanes.length} blocked`)
if (completedLanes.length > 0) log(`  completed: [${completedLanes.join(', ')}]`)
if (failures.length > 0) {
  log(`  failed:    [${failures.join(', ')}]`)
  for (const fid of failures) {
    const r = results[fid]
    if (r) log(`    ${fid}: ${r.stage} — ${r.error}`)
  }
}
if (skippedLanes.length > 0) log(`  skipped:   [${skippedLanes.join(', ')}]`)
const followUpLanes = Object.keys(results).filter(id => (results[id]?.follow_ups || 0) > 0)
if (followUpLanes.length > 0) {
  log(`  skeptic minority findings (filed at Closeout): [${followUpLanes.map(id => `${id}:${results[id].follow_ups}`).join(', ')}]`)
}
if (blockedLanes.length > 0) {
  log(`  blocked:   [${blockedLanes.join(', ')}]`)
  for (const bid of blockedLanes) {
    const r = results[bid]
    if (r) log(`    ${bid}: ${r.error}`)
  }
}
log(`${'═'.repeat(60)}`)

// ── Triage ──

// A GREEN blocked on files outside its scope is a lane-plan defect, not a
// dependency block: it is triaged even when no lane failed (caliper BUG L).
const laneNeedsWrite = blockedLanes.filter(id => Array.isArray(results[id]?.needs_write))
if (failures.length > 0 || laneNeedsWrite.length > 0) {
  log('── Triage ──')
  try {
    const triage = await workflow(
      { scriptPath: sk('datum-tdd-act-triage') },
      { failures: [...failures, ...laneNeedsWrite], blocked: blockedLanes.filter(id => !laneNeedsWrite.includes(id)).map(id => results[id]), results, lanePlan, runId, epicBranch, agentTypes: agentTypeArgs() },
    ) as { filed?: number; consumer_findings?: number; skipped?: number } | null
    log(`Triage: ${triage?.filed ?? 0} filed, ${triage?.consumer_findings ?? 0} consumer finding(s), ${triage?.skipped ?? 0} skipped`)
  } catch (exc) {
    // Triage is reporting; a crash there must not turn finished lanes into an Act crash.
    log(`[warn] triage_workflow_failed: ${(exc as Error).message} — lane failures are still recorded above`)
  }
}

export const __workflowResult = {
  runId,
  total: lanePlan.total_lanes,
  completed: completedLanes.length,
  failed: failures.length,
  skipped: skippedLanes.length,
  blocked: blockedLanes.filter(id => !laneNeedsWrite.includes(id)).length,
  approval: laneNeedsWrite.length,
  failedLanes: failures,
  skippedLanes,
  approvalLanes: laneNeedsWrite,
  needsApproval: Object.fromEntries(laneNeedsWrite.map(id => [id, results[id]?.error || 'green_blocked_needs_write'])),
  blockedLanes,
  completedLanes,
}
