#!/usr/bin/env python3
"""Seed CURRENT_STATE.md and ROADMAP.md if missing."""

import json
import sys
from pathlib import Path

# Fix relative imports
sys.path.insert(0, str(Path(__file__).parent.parent))
from datum.path_utils import assets_dir


def main() -> None:
    seeded = []

    # Seed quality profiles
    profiles_dir = Path(".datum/profiles")
    profiles_dir.mkdir(parents=True, exist_ok=True)
    for profile in ("quality.yaml", "environment.yaml"):
        dest = profiles_dir / profile
        if not dest.exists():
            template = assets_dir() / f"templates/{profile}"
            if template.exists():
                dest.write_text(template.read_text())
                seeded.append(str(dest))

    cs = Path("CURRENT_STATE.md")
    if not cs.exists():
        template = assets_dir() / "templates/CURRENT_STATE.md"
        if template.exists():
            cs.write_text(template.read_text())
        else:
            cs.write_text(
                "# Current State\n\n*Generated by datum init. Update after each epic.*\n"
            )
        seeded.append(str(cs))

    rm = Path("ROADMAP.md")
    if not rm.exists():
        template = assets_dir() / "templates/ROADMAP.md"
        if template.exists():
            rm.write_text(template.read_text())
        else:
            rm.write_text("# Roadmap\n\n## In Progress\n\n## Planned\n\n## Completed\n")
        seeded.append(str(rm))

    adr_dir = Path("docs/adr")
    adr_dir.mkdir(parents=True, exist_ok=True)
    adr_template = adr_dir / "000-template.md"
    if not adr_template.exists():
        src_template = assets_dir() / "templates/000-madr-template.md"
        if src_template.exists():
            adr_template.write_text(src_template.read_text())
            seeded.append(str(adr_template))

    practice_dir = Path("docs/practice")
    practice_dir.mkdir(parents=True, exist_ok=True)
    practice_readme = practice_dir / "README.md"
    if not practice_readme.exists():
        practice_readme.write_text("# Practice Ledger\n\nRecord manual manager interventions and roadmap decisions here before formal tooling is built to automate them.\n")
        seeded.append(str(practice_readme))

    print(json.dumps({"ok": True, "seeded": seeded}))


if __name__ == "__main__":
    main()
