"""`datum lane-plan-digest`: the compact, deterministic view of lane-plan.json
the Act scheduler needs in-script.

Relaying the whole lane-plan.json through a datum-cli runner is not viable:
an LLM echo normalised "§4" to "§ 4" inside acceptance criteria (changing
spec hashes), and the base64 chunk relay that replaced it was GENERATED by
the runner past ~2.7 KB rather than copied (elonchesd run wf_5791e11f-693).
The scheduler only needs topology, files and a per-lane spec hash; that is a
few KB a runner echoes reliably and the batch byte-checks (wc -c +
git hash-object of the written digest). Everything else about a lane is
fetched per lane at intake, straight from the file.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from typer.testing import CliRunner

from datum.cli import app
from datum.lane_hash import lane_spec_hash

PLAN = {
    "lanes": {
        "task-001": {
            "title": "A — “quoted” §4",
            "files": ["src/a.py", "tests/test_a.py"],
            "reads": [],
            "depends_on": [],
            "acceptance_criteria": [
                "a(input) returns 1 for §4.1",
                "a(bad) raises ValueError",
            ],
            "red_note": "call a() and assert",
            "kind": "behavioral",
            "stage": "queued",
            "github_issue": 12,
        },
        "task-002": {
            "title": "B",
            "files": ["src/b.py"],
            "reads": ["src/a.py"],
            "depends_on": ["task-001"],
            "acceptance_criteria": ["b() returns 2"],
            "test_command": "uv run pytest tests/b",
            "green_model": "opus",
        },
    },
    "topological_order": ["task-001", "task-002"],
    "total_lanes": 2,
}


@pytest.fixture
def plan_path(tmp_path: Path) -> Path:
    p = tmp_path / "lane-plan.json"
    p.write_text(json.dumps(PLAN, indent=2, ensure_ascii=False))
    return p


def _run(args: list[str]):
    return CliRunner().invoke(app, ["lane-plan-digest", *args])


def test_digest_is_compact_sorted_json_with_topology_and_per_lane_metadata(
    plan_path: Path,
):
    res = _run(["--plan", str(plan_path)])
    assert res.exit_code == 0, res.output
    out = res.output
    assert "\n" not in out.strip(), "digest must be one compact line"
    digest = json.loads(out)
    assert digest["schema_version"] == 1
    assert digest["total_lanes"] == 2
    assert digest["topological_order"] == ["task-001", "task-002"]
    assert list(digest["lanes"]) == ["task-001", "task-002"]
    lane = digest["lanes"]["task-001"]
    assert lane == {
        "depends_on": [],
        "files": ["src/a.py", "tests/test_a.py"],
        "github_issue": 12,
        "kind": "behavioral",
        "reads": [],
        "spec_hash": lane_spec_hash(PLAN["lanes"]["task-001"]),
        "title": "A — “quoted” §4",
    }
    assert (
        "acceptance_criteria" not in lane
        and "red_note" not in lane
        and "stage" not in lane
    )
    lane2 = digest["lanes"]["task-002"]
    assert lane2["test_command"] == "uv run pytest tests/b"
    assert lane2["green_model"] == "opus"
    assert lane2["spec_hash"] == lane_spec_hash(PLAN["lanes"]["task-002"])
    assert (
        json.dumps(digest, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
        == out.strip()
    )


def test_digest_carries_the_plan_blob_sha_so_a_stale_digest_is_detectable(
    plan_path: Path,
):
    import subprocess

    res = _run(["--plan", str(plan_path)])
    digest = json.loads(res.output)
    sha = subprocess.run(
        ["git", "hash-object", str(plan_path)],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    assert digest["lane_plan_sha"] == sha


def test_out_writes_exactly_the_stdout_bytes(plan_path: Path, tmp_path: Path):
    out_path = tmp_path / "digest.json"
    res = _run(["--plan", str(plan_path), "--out", str(out_path)])
    assert res.exit_code == 0, res.output
    assert out_path.read_bytes() == res.output.encode("utf-8")
    assert res.output.endswith("\n")


def test_missing_or_malformed_plan_is_json_error_exit_1(tmp_path: Path):
    res = _run(["--plan", str(tmp_path / "nope.json")])
    assert res.exit_code == 1
    assert "nope.json" in json.loads(res.output)["error"]
    bad = tmp_path / "bad.json"
    bad.write_text("{not json")
    res = _run(["--plan", str(bad)])
    assert res.exit_code == 1
    assert "error" in json.loads(res.output)
    no_lanes = tmp_path / "nolanes.json"
    no_lanes.write_text(json.dumps({"topological_order": []}))
    res = _run(["--plan", str(no_lanes)])
    assert res.exit_code == 1
    assert "lanes" in json.loads(res.output)["error"]
