"""Compact, deterministic digest of lane-plan.json for the Act scheduler.

Relaying the whole lane-plan.json through a datum-cli runner is not viable:
an LLM echo normalised "§4" to "§ 4" inside acceptance criteria (changing
spec hashes, elonchesd run wf_6bfbd9f2-510), and the base64 chunk relay
that replaced it was GENERATED by the runner past ~2.7 KB rather than
copied (wf_5791e11f-693). The scheduler only needs topology, files and a
per-lane spec hash — a few KB a runner echoes reliably, byte-checked by the
batch (wc -c + git hash-object of the written digest). Everything else
about a lane (acceptance criteria, notes) is fetched per lane at intake,
straight from the file in the lane's worktree.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

from datum.lane_hash import lane_spec_hash

SCHEMA_VERSION = 1

# Lane fields the scheduler and the lane runner read in-script. Anything not
# listed (acceptance_criteria, red_note, stage, description, ...) stays in
# the file and is fetched per lane at intake.
_LANE_FIELDS = (
    "title",
    "files",
    "reads",
    "depends_on",
    "kind",
    "github_issue",
    "test_command",
    "green_model",
    "expect_tests_pass",
)


class DigestError(ValueError):
    """The plan could not be digested; the message is safe to print as JSON."""


def build_digest(plan: dict, lane_plan_sha: str) -> dict:
    """Pure: the digest dict for a parsed lane plan."""
    lanes = plan.get("lanes")
    if not isinstance(lanes, dict) or not lanes:
        raise DigestError("lane plan has no lanes object")
    order = plan.get("topological_order")
    if not isinstance(order, list):
        raise DigestError("lane plan has no topological_order list")
    digest_lanes: dict[str, dict] = {}
    for lane_id in sorted(lanes):
        lane = lanes[lane_id]
        if not isinstance(lane, dict):
            raise DigestError(f"lane {lane_id!r} is not an object")
        entry: dict = {}
        for field in _LANE_FIELDS:
            if field in lane and lane[field] is not None:
                entry[field] = lane[field]
        entry.setdefault("files", [])
        entry.setdefault("reads", [])
        entry.setdefault("depends_on", [])
        entry["spec_hash"] = lane_spec_hash(lane)
        digest_lanes[lane_id] = entry
    return {
        "schema_version": SCHEMA_VERSION,
        "lane_plan_sha": lane_plan_sha,
        "total_lanes": int(plan.get("total_lanes") or len(lanes)),
        "topological_order": list(order),
        "lanes": digest_lanes,
    }


def dumps_digest(digest: dict) -> str:
    """One compact line plus a trailing newline — the exact bytes `--out` writes."""
    return (
        json.dumps(digest, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
        + "\n"
    )


def digest_plan_file(plan_path: Path) -> str:
    if not plan_path.is_file():
        raise DigestError(f"lane plan not found: {plan_path}")
    try:
        plan = json.loads(plan_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise DigestError(f"lane plan is not valid JSON: {plan_path}: {exc}") from exc
    sha = subprocess.run(
        ["git", "hash-object", str(plan_path)],
        capture_output=True,
        text=True,
        check=False,
    )
    if sha.returncode != 0:
        raise DigestError(
            f"git hash-object failed for {plan_path}: {sha.stderr.strip()}"
        )
    return dumps_digest(build_digest(plan, sha.stdout.strip()))
