#!/usr/bin/env python3
"""Seed CURRENT_STATE.md and ROADMAP.md if missing."""

import json
import sys
from pathlib import Path

# Fix relative imports
sys.path.insert(0, str(Path(__file__).parent.parent))
from datum.path_utils import templates_dir


def main() -> None:
    seeded = []

    # Seed quality profiles
    profiles_dir = Path(".datum/profiles")
    profiles_dir.mkdir(parents=True, exist_ok=True)
    for profile in ("quality.yaml", "environment.yaml"):
        dest = profiles_dir / profile
        if not dest.exists():
            template = templates_dir() / f"{profile}"
            if template.exists():
                dest.write_text(template.read_text())
                seeded.append(str(dest))

    cs = Path("CURRENT_STATE.md")
    if not cs.exists():
        template = templates_dir() / "CURRENT_STATE.md"
        if template.exists():
            cs.write_text(template.read_text())
        else:
            cs.write_text(
                "# Current State\n\n*Generated by datum init. Update after each epic.*\n"
            )
        seeded.append(str(cs))

    rm = Path("ROADMAP.md")
    if not rm.exists():
        template = templates_dir() / "ROADMAP.md"
        if template.exists():
            rm.write_text(template.read_text())
        else:
            rm.write_text("# Roadmap\n\n## In Progress\n\n## Planned\n\n## Completed\n")
        seeded.append(str(rm))

    adr_dir = Path("docs/adr")
    adr_dir.mkdir(parents=True, exist_ok=True)
    adr_template = adr_dir / "000-template.md"
    if not adr_template.exists():
        src_template = templates_dir() / "000-madr-template.md"
        if src_template.exists():
            adr_template.write_text(src_template.read_text())
            seeded.append(str(adr_template))

    practice_dir = Path("docs/practice")
    practice_dir.mkdir(parents=True, exist_ok=True)
    practice_readme = practice_dir / "README.md"
    if not practice_readme.exists():
        practice_readme.write_text(
            "# Practice Ledger\n\nRecord manual manager interventions and roadmap decisions here before formal tooling is built to automate them.\n"
        )
        seeded.append(str(practice_readme))

    seeded.extend(seed_agents_md())

    print(json.dumps({"ok": True, "seeded": seeded}))


AGENTS_MD_HEADER = """# AGENTS.md

This is the single source of truth for all AI coding agents working in this repository.
All tool-specific files (CLAUDE.md, GEMINI.md, etc.) redirect here.

"""

TOOL_REDIRECT = "# {tool_name} Instructions\n\nAll agent instructions live in [AGENTS.md](AGENTS.md). Read that file.\n"

TOOL_FILES = {
    "CLAUDE.md": "Claude Code",
    "GEMINI.md": "Gemini CLI",
    "CODEX.md": "Codex",
    "KIRO.md": "Kiro",
    "COPILOT.md": "Copilot",
}


def seed_agents_md() -> list[str]:
    seeded = []

    agents = Path("AGENTS.md")
    if not agents.exists():
        agents.write_text(AGENTS_MD_HEADER)
        seeded.append(str(agents))

    for filename, tool_name in TOOL_FILES.items():
        path = Path(filename)
        content = path.read_text() if path.exists() else ""
        redirect_line = (
            "All agent instructions live in [AGENTS.md](AGENTS.md). Read that file."
        )
        if redirect_line not in content:
            path.write_text(TOOL_REDIRECT.format(tool_name=tool_name))
            seeded.append(str(path))

    return seeded


if __name__ == "__main__":
    main()
