#!/usr/bin/env python3
"""Seed CURRENT_STATE.md and ROADMAP.md if missing."""

import json
from pathlib import Path

from datum.path_utils import templates_dir


def seed_hooks() -> list[str]:
    """Copy all datum hooks to the target project's .datum/hooks/."""
    from datum.path_utils import assets_dir

    src_hooks = assets_dir() / "hooks"
    if not src_hooks.exists():
        return []

    dest_hooks = Path(".datum/hooks")
    dest_hooks.mkdir(parents=True, exist_ok=True)
    seeded = []
    for hook in src_hooks.glob("*.sh"):
        dest = dest_hooks / hook.name
        if not dest.exists() or dest.read_text() != hook.read_text():
            dest.write_text(hook.read_text())
            dest.chmod(0o755)
            seeded.append(str(dest))
    for hook in src_hooks.glob("*.py"):
        dest = dest_hooks / hook.name
        if not dest.exists() or dest.read_text() != hook.read_text():
            dest.write_text(hook.read_text())
            seeded.append(str(dest))
    return seeded


def seed_config() -> list[str]:
    """Seed .datum/config.toml from defaults if missing."""
    from datum.path_utils import assets_dir

    config_dest = Path(".datum/config.toml")
    if config_dest.exists():
        return []

    default_src = assets_dir() / "config.toml.default"
    if not default_src.exists():
        return []

    config_dest.parent.mkdir(parents=True, exist_ok=True)
    config_dest.write_text(default_src.read_text())
    return [str(config_dest)]


def seed_lane_tools() -> list[str]:
    """Create scripts/lane-tools/ directory with README."""
    from datum.path_utils import skill_root

    lt_dir = Path("scripts/lane-tools")
    lt_dir.mkdir(parents=True, exist_ok=True)
    seeded = []

    src_readme = skill_root() / "scripts" / "lane-tools" / "README.md"
    dest_readme = lt_dir / "README.md"
    if not dest_readme.exists() and src_readme.exists():
        dest_readme.write_text(src_readme.read_text())
        seeded.append(str(dest_readme))

    src_manifest = skill_root() / "scripts" / "lane-tools" / "manifest.toml"
    dest_manifest = lt_dir / "manifest.toml"
    if not dest_manifest.exists() and src_manifest.exists():
        dest_manifest.write_text(src_manifest.read_text())
        seeded.append(str(dest_manifest))

    return seeded


def main() -> None:
    seeded = []

    # Seed hooks, config, and lane-tools
    seeded.extend(seed_hooks())
    seeded.extend(seed_config())
    seeded.extend(seed_lane_tools())

    # Seed quality profiles
    profiles_dir = Path(".datum/profiles")
    profiles_dir.mkdir(parents=True, exist_ok=True)
    for profile in ("quality.yaml", "environment.yaml"):
        dest = profiles_dir / profile
        if not dest.exists():
            template = templates_dir() / f"{profile}"
            if template.exists():
                dest.write_text(template.read_text())
                seeded.append(str(dest))

    cs = Path("CURRENT_STATE.md")
    if not cs.exists():
        template = templates_dir() / "CURRENT_STATE.md"
        if template.exists():
            cs.write_text(template.read_text())
        else:
            cs.write_text(
                "# Current State\n\n*Generated by datum init. Update after each epic.*\n"
            )
        seeded.append(str(cs))

    rm = Path("ROADMAP.md")
    if not rm.exists():
        template = templates_dir() / "ROADMAP.md"
        if template.exists():
            rm.write_text(template.read_text())
        else:
            rm.write_text("# Roadmap\n\n## In Progress\n\n## Planned\n\n## Completed\n")
        seeded.append(str(rm))

    adr_dir = Path("docs/adr")
    adr_dir.mkdir(parents=True, exist_ok=True)
    adr_template = adr_dir / "000-template.md"
    if not adr_template.exists():
        src_template = templates_dir() / "000-madr-template.md"
        if src_template.exists():
            adr_template.write_text(src_template.read_text())
            seeded.append(str(adr_template))

    practice_dir = Path("docs/practice")
    practice_dir.mkdir(parents=True, exist_ok=True)
    practice_readme = practice_dir / "README.md"
    if not practice_readme.exists():
        practice_readme.write_text(
            "# Practice Ledger\n\nRecord manual manager interventions and roadmap decisions here before formal tooling is built to automate them.\n"
        )
        seeded.append(str(practice_readme))

    seeded.extend(seed_agents_md())

    print(json.dumps({"ok": True, "seeded": seeded}))


AGENTS_MD_HEADER = """# AGENTS.md

This is the single source of truth for all AI coding agents working in this repository.
All tool-specific files (CLAUDE.md, GEMINI.md, etc.) redirect here.

"""

LOCAL_LLM_AGENTS_SECTION = """
## Local LLM — Multi-Turn Orchestration

When a pipeline phase uses local Gemma inference, ALWAYS spawn a subagent (Agent tool
with `model: "sonnet"`) that imports and calls `datum.local_llm.run_phase()` from Python.
NEVER invoke `datum local-llm` via Bash. The CLI exists for human testing only.

### How it works

`run_phase()` auto-routes to multi-turn mode when `[multi_turn]` is enabled for a phase
in `config.toml`. The flow:

1. **Planning turn** — Gemma analyzes the problem, outputs a `StepPlan` (list of actions)
2. **Execution turns** — Gemma executes each step, outputs `StepResult` with confidence score
3. **Synthesis turn** — Gemma combines all findings into the phase's final schema

### Escalation rules

- If any turn triggers repetition, context overflow, or the model says `ESCALATE` → escalate to Claude
- If confidence stays below `confidence_threshold` after retries → escalate
- If total wall-clock exceeds `timeout_s` → escalate
- The orchestrator retries with Claude using the accumulated context as a head start

### Key parameters (all in `config.toml` under `[multi_turn]`)

| Parameter | Default | What it does |
|-----------|---------|-------------|
| `max_turns` | 5 | Max reasoning turns before forced escalation |
| `timeout_s` | 300 | Total wall-clock budget for all turns |
| `turn_timeout_s` | 90 | Max wall-clock per individual turn |
| `confidence_threshold` | 0.8 | Exit early when confidence >= this |
| `temperature_schedule` | fixed | `fixed` / `rising` / `falling` / `u_curve` |
| `context_reserve_pct` | 20 | % of context window reserved for synthesis |
| `retry_on_low_confidence` | true | Retry a turn if confidence < threshold |
| `max_retries_per_turn` | 2 | Max retries per turn before accepting best |
| `planning_turn` | true | Turn 0 produces a step plan |
| `verification_turn` | true | Final turn synthesizes into phase schema |

Per-phase overrides go in `[multi_turn.phase_overrides.<phase>]`.

### Subagent pattern

```python
from datum.local_llm import run_phase

result = run_phase(
    phase="triage",
    prompt=prompt_text,
    schema=TriageDecision,       # optional: Pydantic schema for structured output
    mt_overrides={"max_turns": 3} # optional: override any multi-turn param
)

if result["escalated"]:
    # retry with Claude, pass result["turns"] as context
    ...
else:
    answer = result["result"]
```
"""

TOOL_REDIRECT = "# {tool_name} Instructions\n\nAll agent instructions live in [AGENTS.md](AGENTS.md). Read that file.\n"

TOOL_FILES = {
    "CLAUDE.md": "Claude Code",
    "GEMINI.md": "Gemini CLI",
    "CODEX.md": "Codex",
    "KIRO.md": "Kiro",
    "COPILOT.md": "Copilot",
}


def seed_agents_md() -> list[str]:
    seeded = []

    agents = Path("AGENTS.md")
    if not agents.exists():
        agents.write_text(AGENTS_MD_HEADER + LOCAL_LLM_AGENTS_SECTION)
        seeded.append(str(agents))
    else:
        content = agents.read_text()
        if "Local LLM" not in content and "local_llm" not in content:
            agents.write_text(content.rstrip() + "\n" + LOCAL_LLM_AGENTS_SECTION)
            seeded.append(str(agents) + " (local-llm section added)")

    for filename, tool_name in TOOL_FILES.items():
        path = Path(filename)
        content = path.read_text() if path.exists() else ""
        redirect_line = (
            "All agent instructions live in [AGENTS.md](AGENTS.md). Read that file."
        )
        if redirect_line not in content:
            if content.strip():
                # Prepend redirect to existing content, don't nuke it
                path.write_text(
                    TOOL_REDIRECT.format(tool_name=tool_name) + "\n" + content
                )
            else:
                path.write_text(TOOL_REDIRECT.format(tool_name=tool_name))
            seeded.append(str(path))

    return seeded


if __name__ == "__main__":
    main()
