# generated by datamodel-codegen:
#   filename:  artifact.schema.json
#   timestamp: 2026-05-22T01:17:42+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict


class Status(Enum):
    ok = 'ok'
    partial = 'partial'
    blocked = 'blocked'
    error = 'error'


class ArtifactEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    datum_version: str
    type: str
    owner: str
    status: Status
    payload: dict[str, Any]
