# generated by datamodel-codegen:
#   filename:  brief-red.schema.json
#   timestamp: 2026-05-22T01:17:42+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class Property(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: str
    category: str
    predicate: constr(min_length=1)


class AcceptanceCriterion(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class FilesToWriteItem(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class UpstreamStub(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    file: constr(min_length=1)
    content: str


class DatumRedBrief(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract_version: Literal['1.0']
    agent_role: Literal['RED']
    task_id: constr(pattern=r'^task-\d+$')
    run_id: constr(pattern=r'^epic-\d+-\d{8}-\d{6}$')
    spec_excerpt: constr(min_length=1)
    properties: list[Property] = Field(..., min_length=1)
    acceptance_criteria: list[AcceptanceCriterion] = Field(..., min_length=1)
    files_to_write: list[FilesToWriteItem] = Field(..., min_length=1)
    red_note: constr(min_length=1)
    introduces_stubs: bool
    stub_files: list[str]
    language: constr(min_length=1)
    framework: constr(min_length=1)
    gitnexus_context: str | None
    upstream_stubs: list[UpstreamStub]
    lane_tools_readme: str
