# generated by datamodel-codegen:
#   filename:  brief-green-continuation.schema.json
#   timestamp: 2026-05-22T01:17:42+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, conint, constr


class Status(Enum):
    fail = 'fail'
    compile_error = 'compile_error'
    runtime_error = 'runtime_error'


class TestSignal(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    status: Status


class DatumGreenContinuationBrief(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract_version: Literal['1.0']
    agent_role: Literal['GREEN']
    turn_type: Literal['continuation']
    task_id: constr(pattern=r'^task-\d+$')
    turn: conint(ge=2)
    green_max_turns: conint(ge=2)
    test_signal: TestSignal
    diff_since_last_attempt: str
    message: constr(min_length=1)
