# generated by datamodel-codegen:
#   filename:  closeout-data.schema.json
#   timestamp: 2026-05-22T01:17:42+00:00

from __future__ import annotations

from typing import Any

from pydantic import AwareDatetime, BaseModel, confloat, conint


class Git(BaseModel):
    commits: list[Any] | None = None
    files_touched: list[str] | None = None
    loc_added: int | None = None
    loc_removed: int | None = None
    loc_net: int | None = None
    per_stage_commit_counts: dict[str, Any] | None = None


class Tasks(BaseModel):
    total: int | None = None
    completed: int | None = None
    failed_terminal: int | None = None
    say_do_ratio: confloat(ge=0.0, le=1.0) | None = None
    per_stage_retries: dict[str, Any] | None = None


class Lane(BaseModel):
    task_id: str | None = None
    final_status: str | None = None
    retries: dict[str, Any] | None = None
    brief_defects: list[Any] | None = None


class Platform(BaseModel):
    pr_url: str | None = None
    pr_number: int | None = None
    review_comments_total: int | None = None
    review_comments_resolved: int | None = None
    closed_issues: list[Any] | None = None


class LaneTool(BaseModel):
    path: str | None = None
    description: str | None = None
    added_in_lane: str | None = None
    times_used_this_epic: int | None = None


class BriefDefect(BaseModel):
    task_id: str
    missing_ac: str
    surfaced_by_stage: str


class Solution(BaseModel):
    slug: str | None = None
    pattern: str | None = None
    evidence: str | None = None


class TokenMetrics(BaseModel):
    total_input: int | None = None
    total_output: int | None = None
    per_phase: dict[str, Any] | None = None
    per_stage_act: dict[str, Any] | None = None
    per_lane: dict[str, Any] | None = None
    vs_prior_epic: dict[str, Any] | None = None


class GitnexusDiff(BaseModel):
    pre_impact_summary: str | None = None
    post_impact_summary: str | None = None
    blast_radius_delta: str | None = None


class CloseoutData(BaseModel):
    run_id: str
    epic_number: conint(ge=1)
    merge_sha: str
    merge_timestamp: AwareDatetime
    git: Git
    tasks: Tasks
    lanes: list[Lane] | None = None
    platform: Platform | None = None
    lane_tools: list[LaneTool] | None = None
    brief_defects: list[BriefDefect] | None = None
    solutions: list[Solution] | None = None
    token_metrics: TokenMetrics
    gitnexus_diff: GitnexusDiff | None = None
