# generated by datamodel-codegen:
#   filename:  follow-up.schema.json
#   timestamp: 2026-05-22T01:17:42+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, Field, constr


class Severity(Enum):
    critical = 'critical'
    high = 'high'
    medium = 'medium'
    low = 'low'
    info = 'info'


class Category(Enum):
    flaky_test = 'flaky_test'
    brief_defect = 'brief_defect'
    coverage_gap = 'coverage_gap'
    efficiency_regression = 'efficiency_regression'
    blast_radius_exceeded = 'blast_radius_exceeded'
    say_do_gap = 'say_do_gap'
    lane_tool_missing_description = 'lane_tool_missing_description'
    token_cost_regression = 'token_cost_regression'
    other = 'other'


class FollowUpIssue(BaseModel):
    dedup_key: str = Field(..., description='Stable key for idempotent filing')
    title: constr(min_length=1)
    body: str
    severity: Severity
    category: Category | None = None
    suggested_labels: list[str] | None = None
    source: str = Field(
        ..., description='Which closeout collector or stage generated this'
    )
    filed_url: str | None = Field(
        None, description='Issue URL after filing, null if not yet filed'
    )
    filed_at: AwareDatetime | None = None
