# generated by datamodel-codegen:
#   filename:  lane-plan.schema.json
#   timestamp: 2026-05-22T01:17:42+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr
from typing import Any


class TopologicalOrderItem(RootModel[constr(pattern=r'^task-\d+$')]):
    root: constr(pattern=r'^task-\d+$')


class Lanes(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: constr(pattern=r'^task-\d+$')
    title: constr(min_length=1)
    files: list[str] = Field(..., min_length=1)
    acceptance_criteria: list[str] = Field(..., min_length=1)
    red_note: constr(min_length=1)
    stage: str


class DatumLanePlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: str
    total_lanes: conint(ge=1)
    topological_order: list[TopologicalOrderItem] = Field(..., min_length=1)
    file_ownership: dict[str, constr(pattern=r'^task-\d+$')]
    lanes: dict[str, Lanes]
    units: dict[str, Any] | None = None
