# generated by datamodel-codegen:
#   filename:  lane-plan.schema.json
#   timestamp: 2026-05-22T01:17:42+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr

from datum.id_pattern import LANE_ID_PATTERN


class TopologicalOrderItem(RootModel[constr(pattern=LANE_ID_PATTERN)]):
    root: constr(pattern=LANE_ID_PATTERN)


class Lanes(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: constr(pattern=LANE_ID_PATTERN)
    slug: constr(pattern=r"^[a-z0-9][a-z0-9-]{2,60}$") | None = None
    title: constr(min_length=1)
    files: list[str] = Field(..., min_length=1)
    acceptance_criteria: list[str] = Field(..., min_length=1)
    red_note: constr(min_length=1)
    stage: str


class DatumLanePlan(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: str
    total_lanes: conint(ge=1)
    topological_order: list[TopologicalOrderItem] = Field(..., min_length=1)
    file_ownership: dict[str, constr(pattern=LANE_ID_PATTERN)]
    lanes: dict[str, Lanes]
    units: dict[str, Any] | None = None
