# generated by datamodel-codegen:
#   filename:  packet.schema.json
#   timestamp: 2026-05-22T01:17:42+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Domain(Enum):
    correctness = 'correctness'
    properties = 'properties'
    security = 'security'
    performance = 'performance'
    architecture = 'architecture'
    observability = 'observability'


class Severity(Enum):
    high = 'high'
    medium = 'medium'
    low = 'low'
    info = 'info'


class Finding(BaseModel):
    id: str
    severity: Severity
    file: str | None = None
    line: int | None = None
    description: str
    suggestion: str | None = None


class ReviewPacket(BaseModel):
    schema_version: str
    domain: Domain
    output_path: str
    diff: str | None = None
    spec_summary: str | None = None
    properties: str | None = None
    findings: list[Finding]
