# generated by datamodel-codegen:
#   filename:  quality.schema.json
#   timestamp: 2026-05-22T01:17:42+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, conint


class RequiredCheck(BaseModel):
    id: str
    preferred_commands: list[str] = Field(..., min_length=1)
    required: bool | None = True


class ReviewDimension(BaseModel):
    id: str
    weight: conint(ge=0)
    required: bool
    pass_: str = Field(..., alias='pass', description='Observable pass condition')


class EvidenceRequirements(BaseModel):
    file_line_references: bool | None = True
    command_outputs: bool | None = True


class BlockingSeverity(Enum):
    critical = 'critical'
    high = 'high'
    medium = 'medium'
    low = 'low'


class PassPolicy(BaseModel):
    required_dimensions_must_pass: bool | None = True
    min_score: conint(ge=0, le=100) | None = 75
    unresolved_high_findings_allowed: conint(ge=0) | None = 0
    blocking_severities: list[BlockingSeverity] | None = ['critical', 'high']


class QualityProfile(BaseModel):
    id: str
    required_checks: list[RequiredCheck] | None = None
    review_dimensions: list[ReviewDimension] | None = None
    evidence_requirements: EvidenceRequirements | None = None
    pass_policy: PassPolicy | None = None
