# generated by datamodel-codegen:
#   filename:  task.schema.json
#   timestamp: 2026-05-22T01:17:42+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, conint, constr


class TaskComplexity(Enum):
    behavioral = 'behavioral'
    structural = 'structural'


class DatumTask(BaseModel):
    id: constr(pattern=r'^task-\d+$')
    title: constr(min_length=1)
    description: str | None = None
    acceptance_criteria: list[str] = Field(..., min_length=1)
    files: list[str] = Field(..., min_length=1)
    depends_on: list[constr(pattern=r'^task-\d+$')] | None = []
    introduces_stubs: bool | None = False
    red_note: constr(min_length=1)
    estimated_loc: conint(ge=0) | None = 0
    task_complexity: TaskComplexity | None = 'behavioral'
