# generated by datamodel-codegen:
#   filename:  tasks.schema.json
#   timestamp: 2026-05-22T01:17:42+00:00

from __future__ import annotations

from pydantic import Field, RootModel

from . import task_schema


class DatumTaskList(RootModel[list[task_schema.DatumTask]]):
    root: list[task_schema.DatumTask] = Field(
        ..., min_length=1, title='DATUM Task List'
    )
