# generated by datamodel-codegen:
#   filename:  brief-refactor.schema.json
#   timestamp: 2026-05-22T01:17:42+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class AcceptanceCriterion(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class FilesToWriteItem(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class ImplementationFile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: constr(min_length=1)
    content: str


class TestFile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: constr(min_length=1)
    content: str


class DatumRefactorBrief(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract_version: Literal['1.0']
    agent_role: Literal['REFACTOR']
    task_id: constr(pattern=r'^task-\d+$')
    run_id: constr(pattern=r'^epic-\d+-\d{8}-\d{6}$')
    spec_excerpt: constr(min_length=1)
    properties: list[Any] = Field(..., min_length=1)
    acceptance_criteria: list[AcceptanceCriterion] = Field(..., min_length=1)
    files_to_write: list[FilesToWriteItem] = Field(..., min_length=1)
    language: constr(min_length=1)
    framework: constr(min_length=1)
    implementation_files: list[ImplementationFile] = Field(..., min_length=1)
    test_files: list[TestFile] = Field(..., min_length=1)
    test_results: str
    gitnexus_impact: str | None
    lane_tools_readme: str
    brief_defects_so_far: list[Any]
