# generated by datamodel-codegen:
#   filename:  brief-green.schema.json
#   timestamp: 2026-05-22T01:17:42+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class AcceptanceCriterion(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class FilesToWriteItem(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Status(Enum):
    fail = 'fail'
    compile_error = 'compile_error'
    runtime_error = 'runtime_error'


class TestSignal(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    status: Status
    assertion_failures: list[Any]
    compile_errors: list[Any]
    runtime_errors: list[Any]


class DatumGreenBrief(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract_version: Literal['1.0']
    agent_role: Literal['GREEN']
    task_id: constr(pattern=r'^task-\d+$')
    run_id: constr(pattern=r'^epic-\d+-\d{8}-\d{6}$')
    spec_excerpt: constr(min_length=1)
    properties: list[Any] = Field(..., min_length=1)
    acceptance_criteria: list[AcceptanceCriterion] = Field(..., min_length=1)
    files_to_write: list[FilesToWriteItem] = Field(..., min_length=1)
    language: constr(min_length=1)
    framework: constr(min_length=1)
    test_signal: TestSignal
    gitnexus_context: str | None
    lane_tools_readme: str
    attempt: conint(ge=1)
