# generated by datamodel-codegen:
#   filename:  candidate-edge-cases.schema.json
#   timestamp: 2026-05-22T01:17:42+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field, constr


class Confidence(Enum):
    high = 'high'
    medium = 'medium'
    low = 'low'


class Verdict(Enum):
    gap = 'gap'
    likely_covered = 'likely_covered'
    out_of_scope = 'out_of_scope'


class RefactorVerdict(Enum):
    real_gap = 'real_gap'
    covered = 'covered'
    not_applicable = 'not_applicable'


class Candidate(BaseModel):
    id: str
    property_id: str
    description: str
    input_specification: str | None = None
    expected_violation: str
    confidence: Confidence | None = None
    verdict: Verdict
    refactor_verdict: RefactorVerdict | None = Field(
        None, description='Filled in by REFACTOR during adversarial review'
    )
    refactor_evidence: str | None = None


class CandidateEdgeCases(BaseModel):
    contract_version: str
    agent_role: Literal['ADVERSARIAL']
    task_id: constr(pattern=r'^task-\d+$')
    no_gaps_found: bool | None = False
    reasoning: str | None = None
    candidates: list[Candidate]
