# generated by datamodel-codegen:
#   filename:  environment.schema.json
#   timestamp: 2026-05-22T01:17:42+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class DefaultModel(Enum):
    reasoning = 'reasoning'
    standard = 'standard'
    fast = 'fast'


class Executor(BaseModel):
    default_model: DefaultModel | None = None


class Shell(Enum):
    auto = 'auto'
    sh = 'sh'
    bash = 'bash'
    cmd = 'cmd'
    powershell = 'powershell'


class RequiredChecks(BaseModel):
    shell: Shell | None = 'auto'


class Network(Enum):
    allow = 'allow'
    approval_required = 'approval_required'
    deny = 'deny'


class SecretsPolicy(Enum):
    allow = 'allow'
    never_read_env = 'never_read_env'
    deny_all = 'deny_all'


class DestructiveCommands(Enum):
    allow = 'allow'
    warn = 'warn'
    deny = 'deny'


class Constraints(BaseModel):
    network: Network | None = 'approval_required'
    secrets_policy: SecretsPolicy | None = 'never_read_env'
    destructive_commands: DestructiveCommands | None = 'deny'


class Comments(BaseModel):
    enabled: bool | None = True
    reply: bool | None = True


class Pr(BaseModel):
    base: str | None = 'main'
    comments: Comments | None = None


class Worktree(BaseModel):
    cleanup: bool | None = True


class EnvironmentProfile(BaseModel):
    id: str
    cwd: str | None = Field(None, description='Absolute path to the repository')
    commands: dict[str, str] | None = Field(
        None, description='Named local commands agents can reference by name'
    )
    executor: Executor | None = None
    required_checks: RequiredChecks | None = None
    constraints: Constraints | None = None
    pr: Pr | None = None
    worktree: Worktree | None = None
