# generated by datamodel-codegen:
#   filename:  lane.schema.json
#   timestamp: 2026-05-22T01:17:42+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, constr


class Stage(Enum):
    queued = 'queued'
    RED = 'RED'
    GREEN = 'GREEN'
    REFACTOR = 'REFACTOR'
    completed = 'completed'
    failed_terminal = 'failed_terminal'


class LanePlanEntry(BaseModel):
    id: constr(pattern=r'^task-\d+$')
    title: str | None = None
    files: list[str] = Field(..., min_length=1)
    acceptance_criteria: list[str] = Field(..., min_length=1)
    red_note: constr(min_length=1)
    introduces_stubs: bool | None = None
    estimated_loc: int | None = None
    depends_on: list[str] | None = None
    signature_deps: list[str] | None = None
    behavior_deps: list[str] | None = None
    file_conflict_with: dict[str, Any] | None = None
    stage: Stage | None = None
