# generated by datamodel-codegen:
#   filename:  state.schema.json
#   timestamp: 2026-05-22T01:17:42+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, conint, constr


class CurrentPhase(Enum):
    discovery = 'discovery'
    refine = 'refine'
    plan = 'plan'
    properties = 'properties'
    act = 'act'
    validate = 'validate'
    review = 'review'
    pr_comments = 'pr_comments'
    closeout = 'closeout'


class Status(Enum):
    pending = 'pending'
    in_progress = 'in_progress'
    completed = 'completed'
    failed = 'failed'
    closeout_pending = 'closeout_pending'


class Phases(BaseModel):
    status: Status | None = None
    model: str | None = None
    artifact: str | None = None
    started_at: AwareDatetime | None = None
    completed_at: AwareDatetime | None = None


class Stage(Enum):
    queued = 'queued'
    RED = 'RED'
    GREEN = 'GREEN'
    REFACTOR = 'REFACTOR'
    completed = 'completed'
    failed_terminal = 'failed_terminal'


class SubStage(Enum):
    stub_committed = 'stub_committed'
    test_committed = 'test_committed'
    verified_red = 'verified_red'


class Lanes(BaseModel):
    stage: Stage | None = None
    sub_stage: SubStage | None = None
    stages: dict[str, Any] | None = None
    files_touched: list[str] | None = None
    depends_on: list[str] | None = None
    blocked_on_dependency: list[str] | None = None
    blocked_on_file_conflict: str | None = None


class Git(BaseModel):
    base_branch: str
    work_branch: str
    head_sha: str | None = None
    pr_url: str | None = None
    merge_sha: str | None = None


class BriefDefect(BaseModel):
    task_id: str
    missing_ac: str
    surfaced_by_stage: str


class LaneToolsAddedItem(BaseModel):
    path: str | None = None
    description: str | None = None
    added_in_lane: str | None = None


class DatumState(BaseModel):
    schema_version: str
    run_id: constr(pattern=r'^epic-\d+-\d{8}-\d{6}$')
    skill_version: str
    current_phase: CurrentPhase
    phases: dict[str, Phases]
    lanes: dict[str, Lanes]
    in_flight_count: conint(ge=0) | None = None
    in_flight_cap: conint(ge=1, le=20) | None = None
    git: Git
    brief_defects: list[BriefDefect] | None = None
    lane_tools_added: list[LaneToolsAddedItem] | None = None
    gitnexus_degraded: bool | None = None
    gitnexus_degraded_log: dict[str, Any] | None = None
    config_hash: str | None = None
    gitnexus_index_sha: str | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
