#!/usr/bin/env python3
"""
Install DATUM pre-commit hooks into the target repo's .git/hooks/.

Usage:
  python3 scripts/bootstrap/install_hooks.py [--dry-run]
"""

import argparse
import json
import shutil
import stat
import sys
from pathlib import Path

# Fix relative imports from bootstrap/ to scripts/
sys.path.insert(0, str(Path(__file__).parent.parent))
from path_utils import assets_dir

HOOKS_SRC = assets_dir() / "hooks"

# Map from hook filename → git hook name
HOOK_MAP: dict[str, str] = {
    "pre-commit-test-ratchet.sh": "pre-commit",
    "pre-commit-lane-tools-manifest.sh": "pre-commit",
    "pre-commit-layer-boundary.sh": "pre-commit",
    "pre-commit-file-size.sh": "pre-commit",
    "pre-commit-tdd-guard.sh": "pre-commit",
    "pre-commit-banned-patterns.sh": "pre-commit",
}

# For tools that support PreToolUse hooks (Claude Code), we also write to .claude/settings.json
PRE_TOOL_USE_HOOKS = ["pre-tool-use-install-interceptor.sh"]


def find_git_root() -> Path | None:
    current = Path.cwd()
    while current != current.parent:
        if (current / ".git").exists():
            return current
        current = current.parent
    return None


def make_executable(path: Path) -> None:
    mode = path.stat().st_mode
    path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def install_pre_commit_hooks(git_root: Path, dry_run: bool) -> list[str]:
    hooks_dir = git_root / ".git" / "hooks"
    installed = []
    missing = []

    # We install via a dispatcher: one pre-commit that calls all DATUM hooks in sequence
    dispatcher_path = hooks_dir / "pre-commit"
    datum_hooks_dir = hooks_dir / "datum"

    if not dry_run:
        datum_hooks_dir.mkdir(parents=True, exist_ok=True)

    # Copy individual hooks to .git/hooks/datum/
    for src_name, hook_type in HOOK_MAP.items():
        src = HOOKS_SRC / src_name
        if not src.exists():
            missing.append(str(src))
            continue
        dest = datum_hooks_dir / src_name
        if not dry_run:
            shutil.copy2(src, dest)
            make_executable(dest)
        installed.append(str(dest))

    if missing:
        print(
            json.dumps(
                {
                    "error": "declared hook file missing",
                    "missing": missing,
                    "message": "DATUM hard-stop hooks must exist before init can proceed.",
                },
                indent=2,
            )
        )
        sys.exit(1)

    # Write or update the dispatcher
    datum_hook_calls = "\n".join(
        f'bash "$GIT_DIR/hooks/datum/{name}"'
        for name in HOOK_MAP
        if (HOOKS_SRC / name).exists()
    )

    dispatcher_content = f"""#!/usr/bin/env bash
# DATUM pre-commit dispatcher — auto-generated by datum init
# Do not edit directly; re-run: python3 scripts/bootstrap/install_hooks.py

GIT_DIR="$(git rev-parse --git-dir)"
{datum_hook_calls}
"""

    if not dry_run:
        # Preserve any existing pre-commit content (prepend DATUM block)
        if dispatcher_path.exists():
            existing = dispatcher_path.read_text()
            if "DATUM pre-commit dispatcher" not in existing:
                # Merge: keep existing, add DATUM block before it
                dispatcher_content = (
                    dispatcher_content + "\n# --- existing hooks ---\n" + existing
                )
        dispatcher_path.write_text(dispatcher_content)
        make_executable(dispatcher_path)
    installed.append(str(dispatcher_path))

    return installed


def install_claude_code_hooks(dry_run: bool) -> list[str]:
    """Add install interceptor to .claude/settings.json for Claude Code."""
    settings_path = Path(".claude/settings.json")
    installed = []

    if not dry_run:
        settings_path.parent.mkdir(parents=True, exist_ok=True)
        settings: dict = {}
        if settings_path.exists():
            with settings_path.open() as f:
                settings = json.load(f)

        hooks = settings.setdefault("hooks", {})
        pre_tool = hooks.setdefault("PreToolUse", [])

        datum_hook = {
            "matcher": "Bash",
            "hooks": [
                {
                    "type": "command",
                    "command": f'bash "{HOOKS_SRC}/pre-tool-use-install-interceptor.sh" "$TOOL_INPUT_COMMAND"',
                }
            ],
        }

        # Don't duplicate
        if not any(
            h.get("hooks", [{}])[0]
            .get("command", "")
            .startswith(f'bash "{HOOKS_SRC}/pre-tool-use-install-interceptor')
            for h in pre_tool
        ):
            pre_tool.append(datum_hook)
            with settings_path.open("w") as f:
                json.dump(settings, f, indent=2)
            installed.append(str(settings_path))

    return installed


def main() -> None:
    parser = argparse.ArgumentParser(description="Install DATUM hooks")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    git_root = find_git_root()
    if not git_root:
        print(json.dumps({"error": "Not in a git repository"}))
        sys.exit(1)

    installed = []
    installed.extend(install_pre_commit_hooks(git_root, args.dry_run))
    installed.extend(install_claude_code_hooks(args.dry_run))

    action = "Would install" if args.dry_run else "Installed"
    print(
        json.dumps(
            {
                "ok": True,
                "dry_run": args.dry_run,
                "message": f"{action} {len(installed)} hook(s)",
                "hooks": installed,
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
